#-------------------------------
# General Site Settings

menu:
- {name: 'Projects', url: ''}
- {name: 'Blog', url: 'pages/blog.html'}
- {name: 'About', url: 'pages/about.html'}
- {name: 'Contact', url: 'pages/contact.html'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Personal portfolio powered by Jekyll and GitHub Pages '
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: 'UA-112060364-3'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'thathungrymind'

#-------------------------------
# About Section

about: >
  # About
  
   Hi～ My name is <b>Haoying Yang</b> and I'm a graduate student at the <b>University of California, Irvine</b>, majoring in Master of Science in Business Analytics, which is a STEM Program combined <b>business</b> and <b>data science</b> enabling us to build data driven solutions under business context. 
  <br><br>
  Having both engineering and business education background, I have been growing huge curiosity and passion for <b>Data</b>, as I believe every business decision is science/art of Probability, and data can provide us the best vision of it. So, I started conducting in data analysis filed through hands-on projects, competitions, master studies, internships, and real-world experience. I have gained ability to build, deliver and present data-driven decisions with variety of tools such as Python, SQL, R, Tableau, Excel, alteryx, etc. 
  <br><br>
  Please feel free to contact me. You can find my contact details [here](https://haoyingyang.github.io/Home/pages/contact.html).

contact: >
  # Contact

  Find me on any of the following platforms:
  <br><br>
  - LinkedIn: [eric-y](https://www.linkedin.com/in/eric-y/)<br>
  - Github: [haoyingyang](https://github.com/haoyingyang)<br>
  - Email: [eric.haoying.yang](eric.haoying.yang@gmail.com)

#-------------------------------
# Work Section

projects:
- {name: 'C-level Job Market Analysis', folder: 'proj-1', file: 'proj-1.html'}
- {name: 'C-level Job Market Analysis', folder: 'proj-1', file: 'projects/executive-market-needs.html'}
- {name: 'Johnson & Johnson Stock Price Analysis and Forecasting', folder: 'proj-2', file: 'projects/JNJ-Stock.html'}
- {name: 'Amazon co-purchase Social Network Analysis', folder: 'proj-3', file: 'projects/Amazon-co-purchase.html'}
- {name: 'K-mean Clustering - Airline Customer Target Marketing', folder: 'proj-4', file: 'projects/customer-clustering.html'}
- {name: 'Microsoft Kaggle Competition - Malware Prediction', folder: 'proj-5', file: 'projects/microsoft-malware.html'}
- {name: 'Super Bowl VIII Prediction', folder: 'proj-6', file: 'projects/superbowl.html'}

#-------------------------------
# Contact Section

social:
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/eric-y/'}
- {icon: 'github', link: 'https://github.com/haoyingyang'}
- {icon: 'instagram', link: 'https://www.instagram.com/haoying_yang/'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
